# ==========================================================
#             VirtualFilter - Configuração v1.5
# ==========================================================
language: en

# Default slots for every player
default-slots:
  abf: 1
  isf: 1
  asf: 1

# Define se o aviso de baú virá ativado por padrão
default-chest-debug-enabled: true

# Notificações de Venda na Action Bar
default-actionbar-enabled: true

storage-type: SQLITE
