# ==========================================================
#             VirtualFilter - Configuração
# ==========================================================
# Language (en/pt)
language: en

# Default slots for every player (initial amount)
default-slots:
  abf: 1
  isf: 1
  asf: 1

# --- NOVO: Notificações de Venda ---
# Define se a Action Bar virá ativada por padrão para novos jogadores.
default-actionbar-enabled: true

# Database type: SQLite
storage-type: SQLITE
